function faQC = makefaQCbuttons(ParentPanel,btn,Fsize)
% creates buttons on panel for Classification options
% called from MITT and ClassifyArrayGUI

faQC.Range = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','set range (Cell number)',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.nigood = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*0.5 btn.height]);
faQC.negood = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2.5 btn.num*btn.height btn.width*0.45 btn.height]);
% use instrument correlation Data
btn.num = btn.num-1;
faQC.Correlation = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','Correlation (%)',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
% value for coherence threshold
faQC.Corthreshold = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);
% use cross-correlation between adjacent time series
btn.num = btn.num-1;
faQC.xcorr = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','xcorr adjacent cells (%)',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.xcorrthreshold = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);

% use Hurther Lemmin w1 w2 
btn.num = btn.num-1;
faQC.w1w2xcorr = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','Hurth/Lemm w1w2 noise ratio',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.w1w2xcorrthreshold = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);

% use percentage of Spikes
btn.num = btn.num-1;
faQC.Spikes = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','Spike threshold (%)',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.SpikeThreshold = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);
% use InertialSlope (Jay)
btn.num = btn.num-1;
faQC.InertialSlope = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','Slope of inertial subrange',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.InertialSlopeThreshold = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);

% use 3rd order polynomial fit
btn.num = btn.num-1;
faQC.PolyFilt = uicontrol('Style','checkbox',...
            'Parent',ParentPanel,...
            'String','3rd order Poly fit (z score)',...
            'Units','centimeters',...
            'BackgroundColor','w',...
            'FontSize',Fsize,...
            'Position',[0 btn.num*btn.height btn.width*2 btn.height]);
faQC.zscore = uicontrol('Style','edit',...
            'Parent',ParentPanel,...
            'Units','centimeters',...
            'FontSize',Fsize,...
            'Position',[btn.width*2 btn.num*btn.height btn.width*.95 btn.height]);
 
end
